### ISSUE TITLE
Using the Llama model instead of Galactica

### ISSUE THREAD

**Issue by lhkhiem28** [acharkq/MolCA#10]
I tried to run your code using the Llama model instead of Galactica but I failed to do so. When I use the arg --opt_model 'meta-llama/Llama-2-7b-chat-hf', I got the below error message
AttributeError: 'LlamaTokenizer' object has no attribute 'mol_token_id'

Does your code work with Llama model? If yes, could you please guide me to move from Galactica to Llama. 

Thank you so much!

**Comment by acharkq** [comment]
Hi Khiem,

Gently notice that the mol token id is manually set in Line 153 - 157 in the model.blip2_opt.py file. You can do the same setup for Llamatokenizer.

Further, you might find my recent work 3D-MoLM relevant to your project, which also uses Llama as the base LM.


https://github.com/lsh0520/3D-MoLM
