### ISSUE TITLE
Evaluation on the IUPAC name prediction. 

### ISSUE THREAD

**Issue by xinbowu2** [acharkq/MolCA#11]
Hi, 

Thanks for sharing the codes! I'd like to know if there are codes and checkpoints for performing evaluations on the IUPAC name prediction.

**Comment by acharkq** [comment]
Hi,

Thanks for your interest on our work. The evaluation and training for the IUPAC name are the same as the molecule captioning task.

**Comment by xinbowu2** [comment]
Thanks! How should I get the IUPAC name prediction dataset and the checkpoint for the IUPAC name prediction task?
