### ISSUE TITLE
Question about data leakage

### ISSUE THREAD

**Issue by ZwormZ** [acharkq/MolCA#6]
I notice that the pre-training dataset is collected from Pubchem. The Chebi-20 and Pcdes dataset is also a subset of Pubchem. It seems that, the paper does not address the issue of redundancy in the downstream task dataset during the pre-training phase, which can result in data leakage.
Is there any redundancy in the pre-training dataset?

**Comment by ZwormZ** [comment]
Hi, I check your released Pubchen324K/pretrain dataset. I found a significant amount of redundancy in the  Pubchen324K/pretrain dataset, ChEBI-20, and PCdes datasets:

pubchem324k_pretrain_duplicate_chebi_valid nums:2369, redundancy rate:71.76613147531052%
pubchem324k_pretrain_duplicate_chebi_test nums:2360, redundancy rate:71.51515151515152%
pubchem324k_pretrain_duplicate_pecdes_valid nums:696, redundancy rate:46.430953969312874%
pubchem324k_pretrain_duplicate_pcdes_test nums:1406, redundancy rate:46.88229409803268%


Here is the code and results of my processing. 
Looking forward to your response!

![image](https://github.com/acharkq/MolCA/assets/52192467/37e121f6-9f79-4a94-b17e-a4f331cff148)
![image](https://github.com/acharkq/MolCA/assets/52192467/f0b15296-409e-47c3-9c22-4f9d0ea9d46d)
![image](https://github.com/acharkq/MolCA/assets/52192467/7f518410-0325-4934-bd2d-41b8209b7af2)
![image](https://github.com/acharkq/MolCA/assets/52192467/f0076a74-cb34-47f5-b77e-80bbcca33eae)
![image](https://github.com/acharkq/MolCA/assets/52192467/25b13ed4-af3b-447c-aa12-ee504fb0c884)
![image](https://github.com/acharkq/MolCA/assets/52192467/006ca7c3-ec22-4b21-8ba9-659e69596286)

**Comment by acharkq** [comment]
Thanks for providing the code and the results.
